services:

  #PHP Service
  app:
    container_name: event-app
    build: .
    volumes:
      - ./eventapp:/var/www
    ports:
      - 9009:80

  #Phpmyadmin Service
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9002:80
    environment:
      - PMA_ARBITRARY=1

  #MySQL Service
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: eventsdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306
